### ISSUE TITLE
Make navbar stick to the top while scrolling

### ISSUE THREAD

**Issue by sonalsk** [iamHrithikRaj/bug-busters-portfolio#5]
## Sticky/Affix Navigation Bar
The navigation bar must stick to the top of the page when it reaches its scroll position.
 
Currently the navigation bar stays in its place. It would be difficult for the user to toggle between different pages via the navigation bar as it scrolls up with the page content. It is generally advised to stick the navigation bar at the top of the page, so it is visible to the user at all times, as it stays fixed at the top while the user is scrolling through the web page.

**Comment by iamHrithikRaj** [comment]
I think the way i implemented it, the nav bar will always stick on top, even if you scroll. One issue thats there is that when the background is light the user will not be able to see that hamburger menu because it has a white color too.

But a possible work around for that issue is use of `mix-blend-mode` in CSS properties to bring that contrast automatically.

**Comment by iamHrithikRaj** [comment]
I will take this ticket
